sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --three

script:
  - flake8
  - pytest

after_success:
  - echo "success!"
  # TODO Build and publish docs