sudo: false
language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --three

script:
  - flake8
  - pytest --cov=fs_gcsfs --cov-branch --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml
