image:
  name: eu.gcr.io/lofty-seer-161814/othoz-docker-base:0.6.0
  username: _json_key
  password: $GCP_DEPLOYMENT_SERVICE_ACCOUNT_KEY_FILE

pipelines:
  default:
  - step:
      script:
      - echo ${GCP_DEPLOYMENT_SERVICE_ACCOUNT_KEY_FILE} > /root/client-secret.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/client-secret.json
      - gcloud auth activate-service-account --key-file /root/client-secret.json
      - gcloud config set project ${GCP_PROJECT_ID}

      - pip install pipenv
      - pipenv install --dev --three

      - flake8
      - python -m pytest