name: fs-gcsfs
channels:
  - defaults
  - conda-forge
dependencies:
  # ---------------------------
  # Actual runtime dependencies
  # ---------------------------
  - python=3.5
  - google-cloud-storage=1.12.0
  - fs=2.1.0

  # ------------------------------------------------------------------------
  # Dependencies for running tests, coverage, style and static code analysis
  # ------------------------------------------------------------------------
  - pytest=3.6.2
  - pytest-cov=2.5.1
  - pytest-xdist=1.22.2
  - flake8=3.5.0
  - pip:
    - codacy-coverage==1.3.11
    - pytest-sugar==0.9.1
